### GET All
GET http://localhost:3000/carreras

### GET Single
GET http://localhost:3000/carreras/1

### PUT Single
POST http://localhost:3000/carreras
Content-Type: application/json

{
  "nombre":"Tecnicatura en Programación",
  "grado":"Universitario",
  "universidad":"UNAHUR"
}


### GET Single
GET http://localhost:3000/carreras/1


### POST Materia
POST http://localhost:3000/carreras/1/materia
Content-Type: application/json

{
  "nombre":"materia1",
  "cuatrimestral":true,
  "anio": 1,
  "carreraId": 1
}

### GET Materias by carrera id
GET http://localhost:3000/carreras/1/materias

